### ISSUE TITLE
TED-TST-2024

### ISSUE THREAD

**Issue by owaski** [RomanKoshkin/toLLMatch#1]
Just wondering if you could release the TED-TST-2024 dataset? It's now hard to get rid of data leakage during evaluation without latest data.

**Comment by RomanKoshkin** [comment]
> Just wondering if you could release the TED-TST-2024 dataset? It's now hard to get rid of data leakage during evaluation without latest data.

It is at `raw_datasets/ted-tst-2024`. Can you get it there, or do you have some other issue?

**Comment by owaski** [comment]
Oh I miss that, thank you!
